ruleset:
  label_needs-info:
    name: "Label issue as needs info"
    events: [ issues ]
    when:
      - action = "opened" or action = "edited"
      - not (body contains "Salary Expectation") or not (body contains "## Meta")
    label: needs info

  label_full-time:
    name: "Label issue as full time"
    events: [ issues ]
    when:
      - action = "opened" or action = "edited"
      - body contains "[x] Full Time"
    label: full time
  label_full-time_r:
    name: "Unlabel issue as full time"
    events: [ issues ]
    when:
      - action = "edited"
      - not (body contains "[x] Full Time")
    label: "-full time"

  label_part-time:
    name: "Label issue as part time"
    events: [ issues ]
    when:
      - action = "opened" or action = "edited"
      - body contains "[x] Part Time"
    label: part time
  label_part-time_r:
    name: "Unlabel issue as part time"
    events: [ issues ]
    when:
      - action = "edited"
      - not (body contains "[x] Part Time")
    label: "-part time"

  label_contract:
    name: "Label issue as contract"
    events: [ issues ]
    when:
      - action = "opened" or action = "edited"
      - body contains "[x] Contract"
    label: contract
  label_contract_r:
    name: "Unlabel issue as contract"
    events: [ issues ]
    when:
      - action = "edited"
      - not (body contains "[x] Contract")
    label: "-contract"

  label_internship:
    name: "Label issue as internship"
    events: [ issues ]
    when:
      - action = "opened" or action = "edited"
      - body contains "[x] Internship"
    label: internship
  label_internship_r:
    name: "Unlabel issue as internship"
    events: [ issues ]
    when:
      - action = "edited"
      - not (body contains "[x] Internship")
    label: "-internship"

  label_remote-ok:
    name: "Label issue as remote ok"
    events: [ issues ]
    when:
      - action = "opened" or action = "edited"
      - body contains "[x] Remote OK"
    label: remote ok
  label_remote-ok_r:
    name: "Unlabel issue as remote ok"
    events: [ issues ]
    when:
      - action = "edited"
      - not (body contains "[x] Remote OK")
    label: "-remote ok"

  label_remote-worldwide:
    name: "Label issue as remote worldwide"
    events: [ issues ]
    when:
      - action = "opened" or action = "edited"
      - body contains "[x] Remote Worldwide"
    label: remote worldwide
  label_remote-worldwide_r:
    name: "Unlabel issue as remote worldwide"
    events: [ issues ]
    when:
      - action = "edited"
      - not (body contains "[x] Remote Worldwide")
    label: "-remote worldwide"

  label_remote-regional:
    name: "Label issue as remote regional"
    events: [ issues ]
    when:
      - action = "opened" or action = "edited"
      - body contains "[x] Remote Regional"
    label: remote regional
  label_remote-regional_r:
    name: "Unlabel issue as remote regional"
    events: [ issues ]
    when:
      - action = "edited"
      - not (body contains "[x] Remote Regional")
    label: "-remote regional"
